service: deaddrop-v2
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x # 👈 Rolled back to stable 18.x to prevent module crashes
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - !GetAtt DeadDropTableV2.Arn
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - arn:aws:s3:::secret-sharer-files-param-123
            - arn:aws:s3:::secret-sharer-files-param-123/*
        - Effect: Allow
          Action:
            - sns:*
          Resource: "*"

functions:
  initiateUpload:
    handler: initiate.handler
    events:
      - http:
          path: v2/initiate
          method: post
          cors: true
  completeUpload:
    handler: complete.handler
    timeout: 30 # 👈 Gives S3 plenty of time to stitch the file
    events:
      - http:
          path: v2/complete
          method: post
          cors: true
  readSecret:
    handler: read.handler
    events:
      - http:
          path: v2/read
          method: post
          cors: true

resources:
  Resources:
    DeadDropTableV2:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SecretSharer-v2
        AttributeDefinitions:
          - AttributeName: secretId
            AttributeType: S
        KeySchema:
          - AttributeName: secretId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST