service: deaddrop-v2
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    # 👈 This passes the exact SNS loud-speaker address to our Lambda!
    SNS_TOPIC_ARN: !Ref DeadDropAuditTopic 
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - !GetAtt DeadDropTableV2.Arn
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - arn:aws:s3:::secret-sharer-files-param-123
            - arn:aws:s3:::secret-sharer-files-param-123/*
        # 🛡️ Give Lambda permission to fire off Emails
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - !Ref DeadDropAuditTopic

functions:
  initiateUpload:
    handler: initiate.handler
    events:
      - http:
          path: v2/initiate
          method: post
          cors: true
  completeUpload:
    handler: complete.handler
    timeout: 30
    events:
      - http:
          path: v2/complete
          method: post
          cors: true
  readSecret:
    handler: read.handler
    events:
      - http:
          path: v2/read
          method: post
          cors: true

resources:
  Resources:
    DeadDropTableV2:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SecretSharer-v2
        AttributeDefinitions:
          - AttributeName: secretId
            AttributeType: S
        KeySchema:
          - AttributeName: secretId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true 

    DeadDropWAF:
      Type: AWS::WAFv2::WebACL
      Properties:
        Name: DeadDrop-DDoS-Protection
        Scope: REGIONAL
        DefaultAction:
          Allow: {}
        VisibilityConfig:
          CloudWatchMetricsEnabled: true
          MetricName: DeadDropWAF
          SampledRequestsEnabled: true
        Rules:
          - Name: BlockSpamBots
            Priority: 1
            Action:
              Block: {}
            Statement:
              RateBasedStatement:
                AggregateKeyType: IP
                Limit: 100 
            VisibilityConfig:
              CloudWatchMetricsEnabled: true
              MetricName: BlockSpamBots
              SampledRequestsEnabled: true

    # 📧 1. The Amazon SNS Email Engine
    DeadDropAuditTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: DeadDrop-Audit-Alerts

    # 📧 2. Your Email Subscription (AWS will send you a confirmation link!)
    DeadDropEmailSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: "paramvadhadiya2@gmail.com" # 🚨 PUT YOUR EMAIL HERE!
        Protocol: email
        TopicArn: !Ref DeadDropAuditTopic